using DataAccess.Repositories.Province; using DataAccess.Services.Common; using DomainModel.ViewModels.Province; using Framework.Common; using Microsoft.EntityFrameworkCore;
namespace DataAccess.Services.Province;
public class ProvinceService(IProvinceRepository repository,IPaginationService pagination):IProvinceService
{
 public Task<List<ProvinceListItem>> GetActiveAsync()=>repository.Query().Where(x=>x.IsActive).OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.ProvinceName).Select(x=>new ProvinceListItem{ProvinceID=x.ProvinceID,ProvinceName=x.ProvinceName,IsActive=x.IsActive,DisplayOrder=x.DisplayOrder,Slug=x.Slug}).ToListAsync();
 public Task<ProvinceDetailsModel?> GetDetailsAsync(int id)=>repository.Query().Where(x=>x.ProvinceID==id).Select(x=>new ProvinceDetailsModel{ProvinceID=x.ProvinceID,ProvinceName=x.ProvinceName,IsActive=x.IsActive,DisplayOrder=x.DisplayOrder,Slug=x.Slug,SeoTitle=x.SeoTitle,SeoDescription=x.SeoDescription,SeoKeywords=x.SeoKeywords,CanonicalUrl=x.CanonicalUrl,OpenGraphImageUrl=x.OpenGraphImageUrl,IsIndexable=x.IsIndexable,IsFollow=x.IsFollow}).FirstOrDefaultAsync();
 public async Task<ProvinceListComplexModel> SearchAsync(ProvinceSearchModel m){var q=repository.Query();if(!string.IsNullOrWhiteSpace(m.Keyword))q=q.Where(x=>x.ProvinceName.Contains(m.Keyword));if(m.IsActive.HasValue)q=q.Where(x=>x.IsActive==m.IsActive);var p=q.OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.ProvinceName).Select(x=>new ProvinceListItem{ProvinceID=x.ProvinceID,ProvinceName=x.ProvinceName,IsActive=x.IsActive,DisplayOrder=x.DisplayOrder,Slug=x.Slug});return new(){Items=await pagination.PaginateAsync(p,m),PageModel=m};}
 public async Task<OperationResult> AddAsync(ProvinceAddEditModel m){var r=new OperationResult("افزودن استان");if(await repository.Query().AnyAsync(x=>x.ProvinceName==m.ProvinceName))return r.ToFailed("این استان قبلاً ثبت شده است.");var e=ProvinceMapper.ToEntity(m);await repository.AddAsync(e);await repository.SaveChangesAsync();return r.ToSuccess("استان اضافه شد.",e.ProvinceID);}
 public async Task<OperationResult> UpdateAsync(int id,ProvinceAddEditModel m){var r=new OperationResult("ویرایش استان");var e=await repository.GetByIdAsync(id);if(e is null)return r.ToFailed("استان پیدا نشد.",id);ProvinceMapper.MapForUpdate(m,e);await repository.SaveChangesAsync();return r.ToSuccess("استان ویرایش شد.",id);}
 public async Task<OperationResult> DeleteAsync(int id){var r=new OperationResult("حذف استان");var e=await repository.GetByIdAsync(id);if(e is null)return r.ToFailed("استان پیدا نشد.",id);if(await repository.HasDependenciesAsync(id))return r.ToFailed("استان دارای شهر یا آگهی مرتبط است و قابل حذف نیست.",id);repository.Remove(e);await repository.SaveChangesAsync();return r.ToSuccess("استان حذف شد.",id);}
}
