using DataAccess.Repositories.City; using DataAccess.Services.Common; using DomainModel.ViewModels.City; using Framework.Common; using Microsoft.EntityFrameworkCore;
namespace DataAccess.Services.City;
public class CityService(ICityRepository repository,IPaginationService pagination):ICityService
{
 public Task<List<CityListItem>> GetByProvinceAsync(int provinceId)=>repository.Query().Where(x=>x.ProvinceID==provinceId&&x.IsActive).OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.CityName).Select(x=>new CityListItem{CityID=x.CityID,CityName=x.CityName,ProvinceID=x.ProvinceID,ProvinceName=x.Province.ProvinceName,IsActive=x.IsActive,DisplayOrder=x.DisplayOrder,Slug=x.Slug}).ToListAsync();
 public Task<CityDetailsModel?> GetDetailsAsync(int id)=>repository.Query().Where(x=>x.CityID==id).Select(x=>new CityDetailsModel{CityID=x.CityID,CityName=x.CityName,ProvinceID=x.ProvinceID,ProvinceName=x.Province.ProvinceName,IsActive=x.IsActive,DisplayOrder=x.DisplayOrder,Slug=x.Slug,SeoTitle=x.SeoTitle,SeoDescription=x.SeoDescription,SeoKeywords=x.SeoKeywords,CanonicalUrl=x.CanonicalUrl,OpenGraphImageUrl=x.OpenGraphImageUrl,IsIndexable=x.IsIndexable,IsFollow=x.IsFollow}).FirstOrDefaultAsync();
 public async Task<CityListComplexModel> SearchAsync(CitySearchModel m){var q=repository.Query();if(!string.IsNullOrWhiteSpace(m.Keyword))q=q.Where(x=>x.CityName.Contains(m.Keyword));if(m.ProvinceID.HasValue)q=q.Where(x=>x.ProvinceID==m.ProvinceID);if(m.IsActive.HasValue)q=q.Where(x=>x.IsActive==m.IsActive);var p=q.OrderBy(x=>x.Province.DisplayOrder).ThenBy(x=>x.DisplayOrder).ThenBy(x=>x.CityName).Select(x=>new CityListItem{CityID=x.CityID,CityName=x.CityName,ProvinceID=x.ProvinceID,ProvinceName=x.Province.ProvinceName,IsActive=x.IsActive,DisplayOrder=x.DisplayOrder,Slug=x.Slug});return new(){Items=await pagination.PaginateAsync(p,m),PageModel=m};}
 public async Task<OperationResult> AddAsync(CityAddEditModel m){var r=new OperationResult("افزودن شهر");if(!await repository.ProvinceExistsAsync(m.ProvinceID))return r.ToFailed("استان انتخاب‌شده پیدا نشد.");if(await repository.Query().AnyAsync(x=>x.ProvinceID==m.ProvinceID&&x.CityName==m.CityName))return r.ToFailed("این شهر قبلاً برای استان انتخاب‌شده ثبت شده است.");var e=CityMapper.ToEntity(m);await repository.AddAsync(e);await repository.SaveChangesAsync();return r.ToSuccess("شهر اضافه شد.",e.CityID);}
 public async Task<OperationResult> UpdateAsync(int id,CityAddEditModel m){var r=new OperationResult("ویرایش شهر");var e=await repository.GetByIdAsync(id);if(e is null)return r.ToFailed("شهر پیدا نشد.",id);if(!await repository.ProvinceExistsAsync(m.ProvinceID))return r.ToFailed("استان انتخاب‌شده پیدا نشد.",id);CityMapper.MapForUpdate(m,e);await repository.SaveChangesAsync();return r.ToSuccess("شهر ویرایش شد.",id);}
 public async Task<OperationResult> DeleteAsync(int id){var r=new OperationResult("حذف شهر");var e=await repository.GetByIdAsync(id);if(e is null)return r.ToFailed("شهر پیدا نشد.",id);if(await repository.HasAdvertisementsAsync(id))return r.ToFailed("این شهر دارای آگهی مرتبط است و قابل حذف نیست.",id);repository.Remove(e);await repository.SaveChangesAsync();return r.ToSuccess("شهر حذف شد.",id);}
}
