using DataAccess.Repositories.SiteSetting; using DomainModel.Models; using DomainModel.ViewModels.SiteSetting; using Framework.Common;
namespace DataAccess.Services.SiteSetting;
public class SiteSettingService(ISiteSettingRepository repository):ISiteSettingService
{
 public async Task<PublicSiteSettingModel> GetPublicAsync(){var s=await repository.GetAsync(false);return s is null?new(){SiteName="تحلیل داده آگهی",IsSiteActive=true}:new(){SiteName=s.SiteName,SiteDescription=s.SiteDescription,LogoPath=s.LogoPath,FaviconPath=s.FaviconPath,FooterText=s.FooterText,InstagramUrl=s.InstagramUrl,TelegramUrl=s.TelegramUrl,LinkedInUrl=s.LinkedInUrl,DefaultSeoTitle=s.DefaultSeoTitle,DefaultSeoDescription=s.DefaultSeoDescription,DefaultSeoKeywords=s.DefaultSeoKeywords,IsSiteActive=s.IsSiteActive};}
 public async Task<SiteSettingEditModel?> GetAdminAsync(){var s=await repository.GetAsync(false);return s is null?null:new(){SiteName=s.SiteName,SiteDescription=s.SiteDescription,LogoPath=s.LogoPath,FaviconPath=s.FaviconPath,FooterText=s.FooterText,InstagramUrl=s.InstagramUrl,TelegramUrl=s.TelegramUrl,LinkedInUrl=s.LinkedInUrl,DefaultSeoTitle=s.DefaultSeoTitle,DefaultSeoDescription=s.DefaultSeoDescription,DefaultSeoKeywords=s.DefaultSeoKeywords,IsSiteActive=s.IsSiteActive};}
 public async Task<OperationResult> UpdateAsync(SiteSettingEditModel m){var r=new OperationResult("تنظیمات سایت");var s=await repository.GetAsync();if(s is null){s=new DomainModel.Models.SiteSetting{SiteName=m.SiteName};await repository.AddAsync(s);}SiteSettingMapper.MapForUpdate(m,s);await repository.SaveChangesAsync();return r.ToSuccess("تنظیمات سایت ذخیره شد.",s.SiteSettingID);}
 public async Task<OperationResult> UpdateLogoAsync(string path){var r=new OperationResult("لوگوی سایت");var s=await repository.GetAsync();if(s is null)return r.ToFailed("تنظیمات سایت پیدا نشد.");s.LogoPath=path;await repository.SaveChangesAsync();return r.ToSuccess("لوگوی سایت ذخیره شد.");}
 public async Task<OperationResult> UpdateFaviconAsync(string path){var r=new OperationResult("آیکن سایت");var s=await repository.GetAsync();if(s is null)return r.ToFailed("تنظیمات سایت پیدا نشد.");s.FaviconPath=path;await repository.SaveChangesAsync();return r.ToSuccess("آیکن سایت ذخیره شد.");}
 public async Task<string?> GetLogoPathAsync()=>(await repository.GetAsync(false))?.LogoPath; public async Task<string?> GetFaviconPathAsync()=>(await repository.GetAsync(false))?.FaviconPath;
}
