using DataAccess.Repositories.Advertisement; using DataAccess.Repositories.Membership; using DataAccess.Repositories.Payment; using DataAccess.Services.Common; using DomainModel.Models; using DomainModel.ViewModels.Membership; using Framework.Common; using Framework.Common.Extensions; using Microsoft.EntityFrameworkCore;
namespace DataAccess.Services.Membership;
public class MembershipService(IMembershipRepository repository,IPaymentRepository paymentRepository,IAdvertisementRepository advertisementRepository,IPaginationService pagination):IMembershipService
{
 public Task<List<MembershipPlanListItem>> GetActivePlansAsync()=>repository.PlanQuery().Where(x=>x.IsActive).OrderBy(x=>x.SortOrder).Select(x=>new MembershipPlanListItem{MembershipPlanID=x.MembershipPlanID,Title=x.Title,Description=x.Description,DurationDays=x.DurationDays,AdvertisementLimit=x.AdvertisementLimit,Price=x.Price,IsActive=x.IsActive,SortOrder=x.SortOrder}).ToListAsync();
 public Task<MembershipPlanDetailsModel?> GetPlanAsync(int id)=>repository.PlanQuery().Where(x=>x.MembershipPlanID==id).Select(x=>new MembershipPlanDetailsModel{MembershipPlanID=x.MembershipPlanID,Title=x.Title,Description=x.Description,DurationDays=x.DurationDays,AdvertisementLimit=x.AdvertisementLimit,Price=x.Price,IsActive=x.IsActive,SortOrder=x.SortOrder,CreateDate=x.CreateDate,UpdateDate=x.UpdateDate}).FirstOrDefaultAsync();
 public async Task<MembershipPlanListComplexModel> SearchAsync(MembershipPlanSearchModel m){var q=repository.PlanQuery();if(!string.IsNullOrWhiteSpace(m.Keyword))q=q.Where(x=>x.Title.Contains(m.Keyword));if(m.IsActive.HasValue)q=q.Where(x=>x.IsActive==m.IsActive);var p=q.OrderBy(x=>x.SortOrder).Select(x=>new MembershipPlanListItem{MembershipPlanID=x.MembershipPlanID,Title=x.Title,Description=x.Description,DurationDays=x.DurationDays,AdvertisementLimit=x.AdvertisementLimit,Price=x.Price,IsActive=x.IsActive,SortOrder=x.SortOrder});return new(){Items=await pagination.PaginateAsync(p,m),PageModel=m};}
 public async Task<CurrentMembershipModel?> GetCurrentAsync(string userId){var m=await repository.GetActiveAsync(userId,false);if(m is null)return null;var count=await advertisementRepository.CountAdvertisementsForMembershipAsync(m.UserMembershipID);var valid=m.IsActive&&m.StartDate<=DateTime.Now&&m.EndDate>=DateTime.Now;return new(){UserMembershipID=m.UserMembershipID,MembershipPlanID=m.MembershipPlanID,MembershipPlanTitle=m.MembershipPlan.Title,StartDate=m.StartDate,StartDatePersian=m.StartDate.ToPersianDate(),EndDate=m.EndDate,EndDatePersian=m.EndDate.ToPersianDate(),AdvertisementLimit=m.MembershipPlan.AdvertisementLimit,CurrentAdvertisementCount=count,RemainingAdvertisements=Math.Max(0,m.MembershipPlan.AdvertisementLimit-count),IsActive=valid};}
 public async Task<OperationResult> PurchaseAsync(string userId,int membershipPlanId)
 {
   var result=new OperationResult("خرید عضویت");var plan=await repository.GetPlanAsync(membershipPlanId,false);if(plan is null||!plan.IsActive)return result.ToFailed("طرح عضویت فعال پیدا نشد.");
   var now=DateTime.Now;var old=await repository.GetActiveMembershipsAsync(userId);foreach(var item in old)item.IsActive=false;
   var payment=new DomainModel.Models.Payment{UserID=userId,MembershipPlanID=plan.MembershipPlanID,Amount=plan.Price,TrackingCode=PaymentMapper.NewTrackingCode(),IsPaid=true,CreateDate=now,PaidDate=now};
   await paymentRepository.AddAsync(payment);
   var membership=new UserMembership{UserID=userId,MembershipPlanID=plan.MembershipPlanID,StartDate=now,EndDate=now.AddDays(plan.DurationDays),PaidAmount=plan.Price,IsActive=true,CreateDate=now};
   await repository.AddUserMembershipAsync(membership);await paymentRepository.SaveChangesAsync();return result.ToSuccess("خرید عضویت با موفقیت شبیه‌سازی شد.",payment.PaymentID);
 }
 public async Task<OperationResult> AddPlanAsync(MembershipPlanAddEditModel m){var r=new OperationResult("افزودن طرح عضویت");var e=MembershipMapper.ToEntity(m);await repository.AddPlanAsync(e);await repository.SaveChangesAsync();return r.ToSuccess("طرح عضویت اضافه شد.",e.MembershipPlanID);}
 public async Task<OperationResult> UpdatePlanAsync(int id,MembershipPlanAddEditModel m){var r=new OperationResult("ویرایش طرح عضویت");var e=await repository.GetPlanAsync(id);if(e is null)return r.ToFailed("طرح عضویت پیدا نشد.",id);MembershipMapper.MapForUpdate(m,e);await repository.SaveChangesAsync();return r.ToSuccess("طرح عضویت ویرایش شد.",id);}
 public async Task<OperationResult> DeleteOrDeactivatePlanAsync(int id){var r=new OperationResult("حذف طرح عضویت");var e=await repository.GetPlanAsync(id);if(e is null)return r.ToFailed("طرح عضویت پیدا نشد.",id);if(await repository.PlanHasUsageAsync(id)){e.IsActive=false;e.UpdateDate=DateTime.Now;await repository.SaveChangesAsync();return r.ToSuccess("این طرح استفاده شده بود و به‌جای حذف غیرفعال شد.",id);}repository.RemovePlan(e);await repository.SaveChangesAsync();return r.ToSuccess("طرح عضویت حذف شد.",id);}
}
